# Exercise 1 Company Data

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import tree

In [2]:
df_c=pd.read_csv('D:/Megha/Desktop/DS assignments/Assignment 12 Random Forest/Company_Data.csv')
df_c

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0     9.50        138      73           11         276    120       Bad   42   
1    11.22        111      48           16         260     83      Good   65   
2    10.06        113      35           10         269     80    Medium   59   
3     7.40        117     100            4         466     97    Medium   55   
4     4.15        141      64            3         340    128       Bad   38   
..     ...        ...     ...          ...         ...    ...       ...  ...   
395  12.57        138     108           17         203    128      Good   33   
396   6.14        139      23            3          37    120    Medium   55   
397   7.41        162      26           12         368    159    Medium   40   
398   5.94        100      79            7         284     95       Bad   50   
399   9.71        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

In [3]:
df_c.dtypes

Sales          float64
CompPrice        int64
Income           int64
Advertising      int64
Population       int64
Price            int64
ShelveLoc       object
Age              int64
Education        int64
Urban           object
US              object
dtype: object

In [4]:
sorted(df_c.Sales.unique())

[0.0,
 0.16,
 0.37,
 0.53,
 0.91,
 1.42,
 1.82,
 2.05,
 2.07,
 2.23,
 2.34,
 2.52,
 2.66,
 2.67,
 2.86,
 2.93,
 2.99,
 3.02,
 3.07,
 3.13,
 3.15,
 3.24,
 3.42,
 3.45,
 3.47,
 3.58,
 3.62,
 3.63,
 3.67,
 3.72,
 3.89,
 3.9,
 3.91,
 3.98,
 4.1,
 4.11,
 4.12,
 4.15,
 4.16,
 4.17,
 4.19,
 4.2,
 4.21,
 4.34,
 4.36,
 4.38,
 4.42,
 4.43,
 4.47,
 4.53,
 4.55,
 4.56,
 4.62,
 4.67,
 4.68,
 4.69,
 4.74,
 4.78,
 4.81,
 4.83,
 4.88,
 4.9,
 4.94,
 4.95,
 4.96,
 4.97,
 4.99,
 5.01,
 5.04,
 5.05,
 5.07,
 5.08,
 5.12,
 5.16,
 5.17,
 5.21,
 5.25,
 5.27,
 5.28,
 5.3,
 5.31,
 5.32,
 5.33,
 5.35,
 5.36,
 5.4,
 5.42,
 5.47,
 5.52,
 5.53,
 5.55,
 5.56,
 5.57,
 5.58,
 5.61,
 5.64,
 5.68,
 5.71,
 5.73,
 5.74,
 5.81,
 5.83,
 5.86,
 5.87,
 5.9,
 5.93,
 5.94,
 5.97,
 5.98,
 5.99,
 6.01,
 6.03,
 6.1,
 6.11,
 6.14,
 6.15,
 6.18,
 6.2,
 6.23,
 6.37,
 6.38,
 6.39,
 6.41,
 6.42,
 6.43,
 6.44,
 6.5,
 6.52,
 6.53,
 6.54,
 6.56,
 6.59,
 6.62,
 6.63,
 6.64,
 6.67,
 6.68,
 6.71,
 6.8,
 6.81,
 6.85,
 6.87,
 6.88,
 6.89,
 6.9

In [5]:
df_c['Sales']=pd.cut(df_c.Sales,bins=[0,6,12,18],labels=['Low','Medium','High'],right=True)
df_c

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0    Medium        138      73           11         276    120       Bad   42   
1    Medium        111      48           16         260     83      Good   65   
2    Medium        113      35           10         269     80    Medium   59   
3    Medium        117     100            4         466     97    Medium   55   
4       Low        141      64            3         340    128       Bad   38   
..      ...        ...     ...          ...         ...    ...       ...  ...   
395    High        138     108           17         203    128      Good   33   
396  Medium        139      23            3          37    120    Medium   55   
397  Medium        162      26           12         368    159    Medium   40   
398     Low        100      79            7         284     95       Bad   50   
399  Medium        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

In [6]:
label_encoder=preprocessing.LabelEncoder()
df_c['ShelveLoc']=label_encoder.fit_transform(df_c.ShelveLoc)
df_c['Urban']=label_encoder.fit_transform(df_c.Urban)
df_c['Sales']=label_encoder.fit_transform(df_c.Sales)
df_c['US']=label_encoder.fit_transform(df_c.US)
df_c

Sales  CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0        2        138      73           11         276    120          0   42   
1        2        111      48           16         260     83          1   65   
2        2        113      35           10         269     80          2   59   
3        2        117     100            4         466     97          2   55   
4        1        141      64            3         340    128          0   38   
..     ...        ...     ...          ...         ...    ...        ...  ...   
395      0        138     108           17         203    128          1   33   
396      2        139      23            3          37    120          2   55   
397      2        162      26           12         368    159          2   40   
398      1        100      79            7         284     95          0   50   
399      2        134      37            0          27    120          1   49   

     Education  Urban  US  
0           17      1   1  
1           10      1   1  
2           12      1   1  
3           14      1   1  
4           13      1   0  
..         ...    ...  ..  
395         14      1   1  
396         11      0   1  
397         18      1   1  
398         12      1   1  
399         16      1   1  

[400 rows x 11 columns]

In [7]:
x=df_c.iloc[:,1:10]
y=df_c.iloc[:,0]

In [8]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=15)

In [9]:
x_train=x_train.values
x_train

array([[130,  37,  13, ...,  37,  13,   0],
       [134,  67,   0, ...,  41,  13,   1],
       [143,  81,   5, ...,  61,  18,   1],
       ...,
       [132,  98,   2, ...,  62,  12,   1],
       [139,  23,   3, ...,  55,  11,   0],
       [114,  43,   0, ...,  57,  10,   0]], dtype=int64)

In [10]:
y_train=y_train.values
y_train

array([2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 0, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 1, 2, 2, 3, 2, 2, 2, 1, 0, 2, 1, 2,
       2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 0, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 2, 1, 2, 2, 2,
       1, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 1, 2,
       2, 1, 1, 2, 0, 1, 2, 2, 2, 2, 1, 2, 1, 1, 1, 2, 2, 0, 2, 1, 0, 2,
       1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1,
       1, 1, 1, 0, 2, 1, 2, 2, 1, 2, 0, 2, 2, 2, 2, 0, 1, 2, 2, 2, 1, 2,
       2, 0, 2, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 0, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 0, 2, 1, 2, 1, 1, 2, 1, 2, 2, 2, 2, 2, 0, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2,
       2, 0, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 2,
       2, 1, 2, 0, 2, 2, 2, 1, 2, 2, 2, 0, 2, 2, 2, 2])

In [11]:
x_test=x_test.values
x_test

array([[133,  31,   1, ...,  42,  18,   1],
       [134,  29,  12, ...,  62,  18,   0],
       [141,  33,   0, ...,  34,  17,   1],
       ...,
       [148,  76,   3, ...,  60,  11,   1],
       [121,  68,   0, ...,  79,  12,   1],
       [115,  65,   0, ...,  60,  17,   0]], dtype=int64)

In [12]:
y_test=y_test.values
y_test

array([1, 0, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 1, 2, 1, 2, 2, 2,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 1, 0, 2, 0, 1, 2, 1,
       2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 2, 0, 0, 1, 2, 2, 2,
       1, 1, 2, 0, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 0, 2, 1,
       2, 2, 0, 2, 2, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 1,
       2, 2, 2, 1, 2, 2, 2, 0, 1, 2])

In [13]:
num_trees = 150
max_features = 3
kfold = KFold(n_splits=10, random_state=7,shuffle=True)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
results = cross_val_score(model, x_train, y_train, cv=kfold)
print(results.mean())

0.7428571428571429


In [14]:
model.fit(x_train,y_train)

RandomForestClassifier(max_features=3, n_estimators=150)

In [15]:
y_pred=model.predict(x_test)

In [16]:
y_pred

array([1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2,
       2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [17]:
model_eval=pd.crosstab(y_pred,y_test)
model_eval

col_0   0   1   2
row_0            
1       0  18   5
2      10  22  65

In [18]:
pd.Series(y_pred,y_test)

1    1
0    2
1    2
2    2
2    2
    ..
2    2
2    2
0    2
1    2
2    2
Length: 120, dtype: int32

In [19]:
#model accuracy
np.mean(y_pred==y_test)

0.6916666666666667

In [20]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

kfold = KFold(n_splits=10, random_state=7,shuffle=True)
cart=DecisionTreeClassifier()
model2 = BaggingClassifier(base_estimator=cart,n_estimators=num_trees, random_state=7)
results = cross_val_score(model2, x_train, y_train, cv=kfold)
print(results.mean())

0.7464285714285714


In [21]:
model2.fit(x_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=150,
                  random_state=7)

In [22]:
y_pred=model2.predict(x_test)
y_pred

array([1, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 2, 0, 2, 2, 1, 2, 2,
       1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2,
       2, 1, 2, 0, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 1, 1, 2, 2, 1, 1,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
model_eval2=pd.crosstab(y_pred,y_test)
model_eval2

col_0  0   1   2
row_0           
0      2   0   0
1      0  22  10
2      8  18  60

In [24]:
np.mean(y_pred==y_test)

0.7

In [25]:
from sklearn.ensemble import AdaBoostClassifier

kfold = KFold(n_splits=10, random_state=7,shuffle=True)
model3 = AdaBoostClassifier(n_estimators=num_trees, random_state=7)
results = cross_val_score(model3, x_train, y_train, cv=kfold)
print(results.mean())

0.5892857142857142


In [26]:
model3.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=150, random_state=7)

In [27]:
y_pred=model3.predict(x_test)
y_pred

array([2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2, 0, 2, 2,
       2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 0, 2, 2])

In [28]:
model_eval3=pd.crosstab(y_pred,y_test)
model_eval3

col_0  0   1   2
row_0           
0      6   3   8
2      4  37  62

In [29]:
np.mean(y_pred==y_test)

0.5666666666666667

# Exercise 2: Fraud check

In [30]:
df_f=pd.read_csv('D:/Megha/Desktop/DS assignments/Assignment 12 Random Forest/Fraud_check.csv')
df_f

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..               ...   ...  
595                7   YES  
596                2   YES  
597                0   YES  
598               17    NO  
599               16    NO  

[600 rows x 6 columns]

In [31]:
sorted(df_f['Taxable.Income'].unique())

[10003,
 10150,
 10163,
 10329,
 10348,
 10379,
 10455,
 10735,
 10870,
 10900,
 10933,
 10987,
 11784,
 11794,
 11804,
 11865,
 12011,
 12072,
 12083,
 12453,
 12470,
 12514,
 12659,
 12682,
 12810,
 13068,
 13571,
 13747,
 14300,
 14310,
 14326,
 14398,
 14422,
 14912,
 15296,
 15491,
 15532,
 15627,
 15673,
 15710,
 15853,
 16082,
 16264,
 16316,
 16320,
 16690,
 16992,
 17183,
 17440,
 17783,
 17957,
 17962,
 18032,
 18192,
 18199,
 18572,
 18888,
 19060,
 19169,
 19184,
 19272,
 19649,
 19925,
 20109,
 20309,
 20391,
 20604,
 20719,
 20851,
 21016,
 21337,
 21696,
 21917,
 21945,
 21966,
 22054,
 22159,
 22187,
 22258,
 22773,
 23075,
 23480,
 23855,
 23884,
 24215,
 24347,
 24370,
 24541,
 24557,
 24987,
 25062,
 25222,
 25766,
 26094,
 26101,
 26128,
 26372,
 26494,
 26679,
 26741,
 26783,
 26793,
 26972,
 27081,
 27143,
 27394,
 27520,
 27684,
 27698,
 27877,
 28449,
 28496,
 28707,
 28764,
 28904,
 29046,
 29222,
 29236,
 29385,
 29543,
 29607,
 29732,
 29916,
 29944,
 30167,


In [32]:
df_f['Taxable.Income']=pd.cut(df_f['Taxable.Income'],bins=[10000,30000,100000],labels=['Risky','Good'],right=True)

In [33]:
df_f

Undergrad Marital.Status Taxable.Income  City.Population  Work.Experience  \
0          NO         Single           Good            50047               10   
1         YES       Divorced           Good           134075               18   
2          NO        Married           Good           160205               30   
3         YES         Single           Good           193264               15   
4          NO        Married           Good            27533               28   
..        ...            ...            ...              ...              ...   
595       YES       Divorced           Good            39492                7   
596       YES       Divorced           Good            55369                2   
597        NO       Divorced           Good           154058                0   
598       YES        Married           Good           180083               17   
599        NO       Divorced           Good           158137               16   

    Urban  
0     YES  
1     YES  
2     YES  
3     YES  
4      NO  
..    ...  
595   YES  
596   YES  
597   YES  
598    NO  
599    NO  

[600 rows x 6 columns]

In [34]:
df_f['Taxable.Income']=label_encoder.fit_transform(df_f['Taxable.Income'])
df_f['Undergrad']=label_encoder.fit_transform(df_f['Undergrad'])
df_f['Marital.Status']=label_encoder.fit_transform(df_f['Marital.Status'])
df_f['Urban']=label_encoder.fit_transform(df_f['Urban'])
df_f

Undergrad  Marital.Status  Taxable.Income  City.Population  \
0            0               2               0            50047   
1            1               0               0           134075   
2            0               1               0           160205   
3            1               2               0           193264   
4            0               1               0            27533   
..         ...             ...             ...              ...   
595          1               0               0            39492   
596          1               0               0            55369   
597          0               0               0           154058   
598          1               1               0           180083   
599          0               0               0           158137   

     Work.Experience  Urban  
0                 10      1  
1                 18      1  
2                 30      1  
3                 15      1  
4                 28      0  
..               ...    ...  
595                7      1  
596                2      1  
597                0      1  
598               17      0  
599               16      0  

[600 rows x 6 columns]

In [35]:
x=df_f.drop('Taxable.Income',axis=1)

In [36]:
y=df_f['Taxable.Income']

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=15)

In [39]:
x_train=x_train.values
y_train=y_train.values
x_test=x_test.values
y_test=y_test.values

In [40]:
num_trees = 150
max_features = 3
kfold = KFold(n_splits=10, random_state=7,shuffle=True)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
results = cross_val_score(model, x_train, y_train, cv=kfold)
print(results.mean())

0.7142857142857143


In [41]:
model.fit(x_train,y_train)

RandomForestClassifier(max_features=3, n_estimators=150)

In [42]:
y_pred=model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0])

In [43]:
model_eval=pd.crosstab(y_pred,y_test)

In [44]:
model_eval

col_0    0   1
row_0         
0      140  29
1       11   0

In [45]:
np.mean(y_test==y_pred)

0.7777777777777778

In [51]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

kfold=KFold(n_splits=15,random_state=15,shuffle=True)
cart=DecisionTreeClassifier()
model2=BaggingClassifier(base_estimator=cart,n_estimators=num_trees,random_state=15)
results=cross_val_score(model2,x_train,y_train,cv=kfold)
print(results.mean())

0.7166666666666666


In [52]:
model2.fit(x_train,y_train)

BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=150,
                  random_state=15)

In [54]:
y_pred=model2.predict(x_test)

In [55]:
model_eval2=pd.crosstab(y_pred,y_test)
model_eval2

col_0    0   1
row_0         
0      140  29
1       11   0

In [56]:
np.mean(y_pred==y_test)

0.7777777777777778

In [58]:
from sklearn.ensemble import AdaBoostClassifier
model3=AdaBoostClassifier(n_estimators=num_trees,random_state=15)
results=cross_val_score(model3,x_train,y_train,cv=kfold)
results.mean()

0.7452380952380954

In [59]:
model3.fit(x_train,y_train)

AdaBoostClassifier(n_estimators=150, random_state=15)

In [60]:
y_pred=model3.predict(x_test)

In [61]:
model_eval3=pd.crosstab(y_pred,y_test)
model_eval3

col_0    0   1
row_0         
0      142  29
1        9   0

In [62]:
np.mean(y_pred==y_test)

0.7888888888888889